.TH DV4LSTART 1

.SH NAME
dv4lstart \- redirect V4L API to access a camcorder from a V4L program

.SH SYNOPSIS
.BI "dvlstart [" options "] " command " [" argument " ...]"
.sp

.SH DESCRIPTION
.B dv4lstart
enables programs using the video4linux API to access a dv1394
(Firewire) camcorder. Using the LD_PRELOAD facility, it intercepts
calls to the V4L API and makes the camcorder's videostream available
to the application given by the
.I command
parameter.

Check that LD_PRELOAD works in your environment by starting

\ \ $ dv4lstart ls -l /dev/video0

The resulting output should look like

crw-rw---- 0 root video 81, 10 Jan  1  1970 /dev/video0

Check your 1394 driver config by starting

\ \ $ gst-launch-0.10 dv1394src \\! dvdemux \\! dvdec \\!  xvimagesink

from your shell. After turning on your camera, a video window should
appear. If this works, dv4lstart should work as well.

.SH OPTIONS
.TP
.BI "\-c, \-\-color\-correction"
Set this option if red objects look blue.
.TP
.BI "\-v, \-\-verbose" \ level
Set the amount of debugging messages. A level of 0 means no output at
all, 1
is the default, 3 enables all messages.
.TP
.B "\-h, \-\-help"
displays a help message

.SH EXAMPLES
The command

\ \ $ dv4lstart v4l-info

outputs some information about the simulated V4L device.

\ \ $ dv4lstart -c gqcam -v /dev/video0 

starts the
.I gqcam
webcam viewer, swapping red and blue colors.

.SH LIMITATIONS
Programs using exotic ways to access the V4L API will not
work.

Some environments don't allow the use of LD_PRELOAD for security
reasons.
.B dv4lstart
will not work there.

If
.B dv4lstart
does not work, try 
.I dv4l
instead.

.SH SEE ALSO
dv4l(1)

